### ISSUE TITLE
The feedback button is not clickable 

### ISSUE THREAD

**Issue by Wladefant** [TUM-Dev/Campus-Flutter#101]
I would suggest leading it to github directly to the configuration screen, where you can choose what to report

**Comment by jakobkoerber** [comment]
Good suggestions, the only issue I have with that is that the user has to sign-in to GitHub... and that shouldn't be necessary to provide feedback imo. Which email clients do you use on your phone?

**Comment by Wladefant** [comment]
Gmail as most of the people I know, but that does not matter, or yes jsut add the redirect to an email client

**Comment by Wladefant** [comment]
That is what the old app does 
![image](https://github.com/TUM-Dev/Campus-Flutter/assets/79611093/6afc960c-88d1-4507-b637-b1d1db381dcd)

**Comment by jakobkoerber** [comment]
> or yes jsut add the redirect to an email client

This is already in place, the Android app was just missing the proper permissions
