### ISSUE TITLE
Enhancement : show my location on the map plus go to my location button

### ISSUE THREAD

**Issue by Wladefant** [TUM-Dev/Campus-Flutter#104]
Showcasing button

![Screenshot_20231003-200025_Maps.jpg](https://github.com/TUM-Dev/Campus-Flutter/assets/79611093/23e9cf87-9887-4f51-ac64-fe770c9e8843)

**Comment by jakobkoerber** [comment]
The Location should be already visible on the map but I added the location button you suggested

**Comment by Wladefant** [comment]
> The Location should be already visible on the map but I added the location button you suggested

Yes i see that now. Didnt saw it on my phone but maybe it is just me

**Comment by jakobkoerber** [comment]
Maybe it's an issue with Android, I will test that soon

**Comment by Wladefant** [comment]
No, on my android tablet it works fine. I suppose I just didnt saw it

**Comment by Wladefant** [comment]
Ok it works. The app didn't have the permission to my location
