### ISSUE TITLE
[BUG] Latest news on home tab not clickable

### ISSUE THREAD

**Issue by Wladefant** [TUM-Dev/Campus-Flutter#106]
Version: 0.2.1

**Comment by jakobkoerber** [comment]
Thanks for contributing! The news are never clickable since the Backend doesn't provide a link :D

**Comment by Wladefant** [comment]
Ok... what are the news for? And why doesnt the backend provide a link? Should we report it?

**Comment by jakobkoerber** [comment]
Feel free to open an issue in the Campus-Backend repo
