### ISSUE TITLE
[Feature] add "online unterlage" notes to courses description so that you can access the needed moodle page directly for example

### ISSUE THREAD

**Issue by Wladefant** [TUM-Dev/Campus-Flutter#124]
![image](https://github.com/TUM-Dev/Campus-Flutter/assets/79611093/a7f184eb-81d1-44e5-8d46-81a8c09ffa2a)

**Comment by Wladefant** [comment]
And another questions is why on [MA0902] the note is shown but on the course (IN0015)

**Comment by jakobkoerber** [comment]
> ![image](https://user-images.githubusercontent.com/79611093/274882864-a7f184eb-81d1-44e5-8d46-81a8c09ffa2a.png)

Unfortunately the API we use does not provide the needed information :(

**Comment by jakobkoerber** [comment]
> And another questions is why on [MA0902] the note is shown but on the course (IN0015)

@Wladefant could explain a little further or provide screenshots?

**Comment by Wladefant** [comment]
>Unfortunately the API we use does not provide the needed information :(
yes that is what I thought, but I think this is needed, so then the api has to change, who is the one managing that?

Here example
1. (IN0015) 
![image](https://github.com/TUM-Dev/Campus-Flutter/assets/79611093/ab15d7ff-f9b4-4d6a-9f6f-7a113e24c5d7) 
![image](https://github.com/TUM-Dev/Campus-Flutter/assets/79611093/cfdc48fd-4d6e-4096-8cd5-d839ef9c3e33)

2. [MA0902] 
![image](https://github.com/TUM-Dev/Campus-Flutter/assets/79611093/b5f1f2c2-4ac5-4613-b546-5ca196507f6b)
![image](https://github.com/TUM-Dev/Campus-Flutter/assets/79611093/30c4a8ef-fb3c-47d1-96de-5efa4adf3e99)

Ok right now you are not able to see both notes, but I can swear that I saw it on the second one before that. and here is an example where it works, so there is some inconsistency here?
![image](https://github.com/TUM-Dev/Campus-Flutter/assets/79611093/ae904899-0b14-4297-97ea-4be41637fe25)

**Comment by jakobkoerber** [comment]
The inconsistency seems to be in the API we use, not me much we can do about that :(
