### ISSUE TITLE
[Feature] Show Cafeteria Details if Cafeteria Name is clicked

### ISSUE THREAD

**Issue by Wladefant** [TUM-Dev/Campus-Flutter#140]
![SmartSelect_20231023_105122](https://github.com/TUM-Dev/Campus-Flutter/assets/79611093/dce35722-c007-42a7-83f0-ecca8bd4130b)
so that when I tap on the cafe, it automatically goes to this screen

![SmartSelect_20231023_105255](https://github.com/TUM-Dev/Campus-Flutter/assets/79611093/f38a30ab-49d6-4685-95d8-d9aab896dc7b)

**Comment by jakobkoerber** [comment]
Where would you expect the tappable area? The name?

**Comment by Wladefant** [comment]
Yes the name for sure. It is even such a blue

**Comment by jakobkoerber** [comment]
> It is even such a blue

Explain please :)

**Comment by Wladefant** [comment]
Link blue haha

**Comment by Wladefant** [comment]
Yes for sure, normally I do this much more thourough, but when I use the app I find some things, and create an issue fast, because I am on my way, so you can either wait a day, or write "not sufficient enough" and I will add information ;)
