### ISSUE TITLE
[Feature] Adjust Zooming Behaviour of Location Maps

### ISSUE THREAD

**Issue by Wladefant** [TUM-Dev/Campus-Flutter#141]
not like that
![SmartSelect_20231023_105454](https://github.com/TUM-Dev/Campus-Flutter/assets/79611093/5f1ea11b-22fd-443b-9fd4-a550d7cb047b)

but like that
![SmartSelect_20231023_105504](https://github.com/TUM-Dev/Campus-Flutter/assets/79611093/b186066a-44ba-43cb-9baf-e7bb879205ee)

**Comment by Wladefant** [comment]
Because why would I be interested in cafes that are 10 km away ;)

**Comment by jakobkoerber** [comment]
Please explain the expected behaviour more detailed:
- Do you want the map zooming in if a cafeteria is selected on the map? 
- Do you want the zoom to be closer from the get go? If so, I don't think that's useful, since all cafeterias should be visible

**Comment by Wladefant** [comment]
ah sorry I see I used the same image two times please look at the editedmessage

**Comment by Wladefant** [comment]
Yes closer from the get go. You could zoom out if you want to see the cafeterias. But why would you want to look at cafeterias when you have many near you.

**Comment by jakobkoerber** [comment]
the reasoning behind that is to get a broader overview of all cafeterias, therefore it as a subjective design decision and there's not right or wrong... I will consider your input though
