### ISSUE TITLE
[Feature] Option to hide weekends in the weekly view

### ISSUE THREAD

**Issue by Q1CHENL** [TUM-Dev/Campus-Flutter#156]
I haven't really had lectures on weekends, and I believe that's the same for many others as well, at least during the lecture period. I think an option to hide weekends in the Calendar would be helpful and will save (horizontal) space to show more details of courses on weekdays.

I think this could be done with `CalendarWeek.workWeek`

**Comment by jakobkoerber** [comment]
Thank you for your feedback! The changes will be released with v0.3.3
