### ISSUE TITLE
[Bug] 404 Responses for NavigaTUM Rooms

### ISSUE THREAD

**Issue by jakobkoerber** [TUM-Dev/Campus-Flutter#159]
for example: https://nav.tum.de/api/get/0.01@0201?lang=en

**Comment by CommanderStorm** [comment]
This will be resolved in a few minutes

![image](https://github.com/TUM-Dev/Campus-Flutter/assets/26258709/700aac45-b059-42ac-b740-d1215c085540)
https://xkcd.com/303/

**Comment by jakobkoerber** [comment]
Can confirm! Thank you for the quick fix 👍🏼
