### ISSUE TITLE
[Enhancement] Allow opening links in lecture information

### ISSUE THREAD

**Issue by Garfield96** [TUM-Dev/Campus-Flutter#168]
**Is your feature request related to a problem? Please describe.**
The old TUM Campus-Android app allowed to open links in the lecture information. This feature is not implemented yet in Campus-Flutter.

**Describe the solution you'd like**
Make links clickable and open the referenced page in the browser.

**Describe alternatives you've considered**
Making the text copiable would also facilitate opening the link, but is still cumbersome.

**Additional context**
Original feature request in Campus-Android: https://github.com/TUM-Dev/Campus-Android/issues/1584

**Comment by jakobkoerber** [comment]
Hey, thank you for your feedback! I added this for lecture details:

![Simulator Screenshot - iPhone 15 Pro - 2023-12-16 at 14 05 11](https://github.com/TUM-Dev/Campus-Flutter/assets/56073945/27cd9600-1c9e-47f2-949b-068d5275909e)

It will be released in Beta with version 4.4.1 sometime in the near future :D
