### ISSUE TITLE
[BUG] Information Mismatch in Lecture Details

### ISSUE THREAD

**Issue by Garfield96** [TUM-Dev/Campus-Flutter#172]
**Describe the bug**
The information shown in the lectures list is incorrect. The list shows a lecture for the next summer semester. However, there is no such lecture in TUMonline. Clicking on the lecture shows the data for the lecture, which took place in the winter term 2021/22. It looks like, the details page shows the information for the oldest occurrence of a lecture.

**To Reproduce**
1. Go to Lectures
2. Open some lectures and compare information shown in the list with the information shown in the details

**Expected behavior**
Information shown in the list should match the information shown in the details.

**Screenshots**
<p float="left">
<img src="https://github.com/TUM-Dev/Campus-Flutter/assets/15248220/d2ea1aa4-2aea-4597-af1c-a808b9fbb288" width="48%">
<img src="https://github.com/TUM-Dev/Campus-Flutter/assets/15248220/fe2c5490-ae6c-4726-bda5-611ead85561e" width="48%">
</p>

**Smartphone (please complete the following information):**
* Phone: Redmi Note 12 Pro+
* OS version: Android 13 TP1A.220624.014
* Language: German

**Additional context**
None

**Comment by jakobkoerber** [comment]
The information shown on the lecture detail page is provided by the TUMonline API and therefore not really an issue regarding Campus-Flutter. We could think of overwriting this locally, but this would also mean that we differ from information provided by TUMonline

**Comment by alexanderstephan** [comment]
In this case, this behavior should also occur in the other TUM Campus Apps, right?

**Comment by jakobkoerber** [comment]
I assume so, yes. Campus-Flutter doesn't manipulate the provided data :) 

The issue was with the _wbservicesbasic.veranstaltungenDetails_ endpoint which serves the wrong semester, in _bugfix/lecture-details-semester_ this is now overwritten with the correct value from the _wbservicesbasic.veranstaltungenEigene_ endpoint
