### ISSUE TITLE
[Enhancement] Show available past calendar events

### ISSUE THREAD

**Issue by kaii-tech** [TUM-Dev/Campus-Flutter#176]
**Describe the bug**
The calendar only shows future events, any past or in progress lectures, personal appointments, etc. do not show in the calendar section.

**To Reproduce**
1. Go to 'Calendar'
2. Click on 'Week or Month'
3. See error

**Expected behaviour**
Must be able to see at all past calendar events.

**Screenshots**
![Screenshot 2023-12-17 at 22 41 07](https://github.com/TUM-Dev/Campus-Flutter/assets/63472188/1db13a16-a8ed-4a03-9d15-44b55863ce83)

**Smartphone (please complete the following information):**
* Phone: iPhone 13 Pro Max
* OS version: 17.1.2
* Language: English

**Additional context**
If it is the way flutter only pulls for future events, is it maybe possible to pull from a week prior so that at least the previous/current week is displayed. 
This issue is not just tied to me, my friends (all iOS & iPadOS) seem to have the same issue.
I'm guessing that this bug is already know, but I didn't see any bug report so I though I'd make one.

Let me know if you'll need anything else!

**Comment by jakobkoerber** [comment]
Hey, thank you for contributing! I wouldn't consider this being a bug since it is expected behavior. The API endpoint does not offer every calendar event from the past. Therefore I would suggest displaying all events the endpoint serves. I hope that's fine for you

**Comment by kaii-tech** [comment]
Hi, I just checked and on the Web App, and it is working correctly, I can see all past events. I guess its an issue with the iOS app then? I don't have a android device to test it on.

Attached Screenshot from Web App showing date (27-30 November):
<img width="1440" alt="image" src="https://github.com/TUM-Dev/Campus-Flutter/assets/63472188/6b4eb872-4bd2-4d60-a53b-13b3f95f4649">

**Comment by jakobkoerber** [comment]
Interesting 😆 let me investigate this

**Comment by kaii-tech** [comment]
Thanks, it's a small thing but really frustrates me.

Let me know if i can help in anyway 😁

**Comment by jakobkoerber** [comment]
Understandable! Thank you for letting me/us know, I appreciate the effort 😄

**Comment by kaii-tech** [comment]
👍🏼
