### ISSUE TITLE
[Enhancement] Clickable Personal Appointments in the Calendar

### ISSUE THREAD

**Issue by kaii-tech** [TUM-Dev/Campus-Flutter#177]
**Is your feature request related to a problem? Please describe.**
I often have overlapping events in the calendar and in the "Week" view sometimes there is no label displayed due to the space. When I click on the event, if it is a personal appointment, it just shows "Connection Error" (tested on iOS and web app). So i have to always go into day view to read the event title/label.

**Describe the solution you'd like**
When clicking on / opening a "Personal Appointment", It should display a pop-up just like with all other calendar events displaying the Title, date & Time, and if possible, any added comments.

**Additional context**
Some context as to why i feel this is important for the main release... In the Aerospace course, some of our lectures have the wrong start/end timings listed in the calendar, we use "Personal Appointments" to remind us of the accurate lecture timings as well as to add our tutor session to our calendar as they are not listed by default. Our Central Exercise most of the time tend to overlap with  our tutor classes and with each other. So we frequently have to press on the event to read the title.
I have attached a screenshot of my calendar bellow.

![IMG_7943](https://github.com/TUM-Dev/Campus-Flutter/assets/63472188/ee4f456f-acf8-48ef-85ef-ed5ad5f03267)

**Comment by kaii-tech** [comment]
I'm not sure if this is possible with the way the API is setup, but it would be amazing if we could also add/edit personal appointments from the app directly.

**Comment by jakobkoerber** [comment]
@kaii-tech would you be willing to authorise a token of your's for me? This would highly improve testing on my side 😄 If so, you can either provide your TUM ID here or for privacy reasons via jakob.koerber@tum.de

**Comment by kaii-tech** [comment]
@jakobkoerber I have sent you an email with the same.

**Comment by jakobkoerber** [comment]
> I'm not sure if this is possible with the way the API is setup, but it would be amazing if we could also add/edit personal appointments from the app directly.

Unfortunately, this is not possible with the current API setup and we don't have a lot of influence on it since it's within the framework of CAMPUSonline ☹️

**Comment by jakobkoerber** [comment]
To mitigate your issue, I added a dialog which shows the title and date of the custom calendar entry. Imo opening a sheet for so few information is not really useful. Let me know if you have more suggestions

![Simulator Screenshot - iPhone 15 Pro - 2023-12-18 at 20 25 15](https://github.com/TUM-Dev/Campus-Flutter/assets/56073945/b27e7ccd-2657-4e03-951a-09764205ec00)

**Comment by CommanderStorm** [comment]
> Unfortunately, this is not possible with the current API setup and we don't have a lot of influence on it since it's within the framework of CAMPUSonline

If you are mssing an API/... please say so ^^
The requested achviements ("Meine Leistungen") API is currently in testing/verification => will be deployed in the next batch of ConnecTUM APIs.
cc @xsrf

**Comment by kaii-tech** [comment]
Yup that works, thanks for the quick replies!

**Comment by xsrf** [comment]
> > I'm not sure if this is possible with the way the API is setup, but it would be amazing if we could also add/edit personal appointments from the app directly.
> 
> Unfortunately, this is not possible with the current API setup and we don't have a lot of influence on it since it's within the framework of CAMPUSonline ☹️

Actually, there is 😉 see #183

**Comment by jakobkoerber** [comment]
> > > I'm not sure if this is possible with the way the API is setup, but it would be amazing if we could also add/edit personal appointments from the app directly.
> > 
> > 
> > Unfortunately, this is not possible with the current API setup and we don't have a lot of influence on it since it's within the framework of CAMPUSonline ☹️
> 
> Actually, there is 😉 see #183

Thanks! I will make sure that we support this feature shortly
