### ISSUE TITLE
Data Safety incorrect on Google Play

### ISSUE THREAD

**Issue by kordianbruck** [TUM-Dev/Campus-Flutter#73]
![image](https://github.com/TUM-Dev/Campus-Flutter/assets/298860/5ce2635a-f7de-4a9e-8d1c-1578bad9e8a1)

Given the app is already released as "production" in Google Play, we should actually correctly fill in the privacy fields. At the very least the app contacts

* TUM Cabe/Sexy/Navigatum Backend, operated by us (1st party)
* TUM Online Backend, operated by the university
* Eat API (Hosted by Github)
* MVV
* Uses location services (locally, but also forwards it to Navigatum/MVV)

**Comment by jakobkoerber** [comment]
On it 👍

@kordianbruck
While accessing the Play Store Console I get the following issue. Would be great if you can take a look at that:
<img width="558" alt="Screenshot 2023-10-05 at 10 23 51" src="https://github.com/TUM-Dev/Campus-Flutter/assets/56073945/08ad7960-e581-47fa-90ca-e1a0298838fe">

**Comment by jakobkoerber** [comment]
I updated the Data Safety via the console and it's submitted for review. I wan't quite sure about every point therefore it would be great if you could take a look at it [here](https://play.google.com/console/u/0/developers/5108654148238694581/app/4974311462229559361/app-content/data-privacy-security)
