### ISSUE TITLE
[Feature] Add License

### ISSUE THREAD

**Issue by Garfield96** [TUM-Dev/Campus-Flutter#77]
**Is your feature request related to a problem? Please describe.**
This project is currently missing a license. Once people start to contribute, this will be difficult to change.

**Describe the solution you'd like**
Add a license.

**Describe alternatives you've considered**
There is no alternative.

**Additional context**
Most TUM-Dev projects use either MIT or GPL-3.0.

**Comment by alexanderstephan** [comment]
It says that it is licensed [GNU GPL v3](http://www.gnu.org/licenses/gpl.html) in the `README`. Not sure if that's enough to be legally binding though.

**Comment by Garfield96** [comment]
Section 4 of the GPL-3.0 states "give all recipients a copy of this License along with the Program" (https://www.gnu.org/licenses/gpl-3.0.de.html). Therefore, I'm not sure whether it is binding.
