### ISSUE TITLE
[BUG] multiple release within a day and without apk? 

### ISSUE THREAD

**Issue by Wladefant** [TUM-Dev/Campus-Flutter#98]
Nice work, everyone. @jakobkoerber thank for the pre releases, but there isn't any apk attached. And you created multiple releases in a day eith different version numbers, is that planned?
![Screenshot_20231003-191145_GitHub.jpg](https://github.com/TUM-Dev/Campus-Flutter/assets/79611093/10fe99ef-6d43-4c86-b9d0-f37d13b9a1e1)

**Comment by jakobkoerber** [comment]
0.2.1 added new functionalities and an immediate bug fix to 0.2.0 therefore the version bump. I don't see the need behind providing .apk files, we don't do that with Campus-Android either. You can test new releases via the Open Beta Program in the Google Play Store. The link can be found in the README.md file.

**Comment by Wladefant** [comment]
Yes alright, just wasnt sure, no deal breaker
